### ISSUE TITLE
The TVL calculation excludes wUSDR, AERO, and TAROT on Base.

### ISSUE THREAD

**Issue by ExtraFi** [DefiLlama/DefiLlama-Adapters#7378] opened 2023-09-05 11:26 UTC
The TVL calculation excludes wUSDR, AERO, and TAROT on Base.

wUSDR base:0x9483ab65847A447e36d21af1CaB8C87e9712ff93
AERO base:0x940181a94A35A4569E4529A3CDfB74e38FD98631
TAROT base:0xF544251D25f3d243A36B07e7E7962a678f952691

```node test projects/extra/index.js ```

--- base ---
USDbC                     2.15 M
WETH                      204.08 k
EXTRA                     129.79 k
DOLA                      141.0797598710204
cbETH                     10.576141969391223
Total: 2.48 M 

------ TVL ------
base                      2.48 M

**Comment by g1nt0ki** [comment] 2023-12-05 13:33
the issue is our coins api is not pricing some of these tokens, looking into it

**Comment by realdealshaman** [comment] 2024-09-26 16:13
this was fixed, closing this issue for now

**Closed by realdealshaman** 2024-09-26 16:13 UTC
